---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: son-monitor-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: son-monitor-manager
        platform: sonata
    spec:
      containers:
      - name: son-monitor-manager
        image: sonatanfv/son-monitor-manager:v4.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        - containerPort: 8888