---
apiVersion: v1
kind: Service
metadata:
  name: tng-gtk-common
  labels:
    app: tng-gtk-common
    platform: sonata
    version: "5"
spec:
  ports:
  - port: 5000
    name: http-common
    targetPort: 5000
  selector:
    app: tng-gtk-common
  type: ClusterIP
