---
# Installation Starts
- name: Installation Starts
  uri:
    url: http://bit.ly/2SMY5z7
    method: GET
    validate_certs: no
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0"
  ignore_errors: True
  when: target == "localhost"

# Deploying VnV Databases

# Deploying VnV Components

# deploy mongo
- import_tasks: mongo.yml
  when: (component == 'database') or
        (component == 'all')

# deploy tng-vnv-lcm
- import_tasks: lcm.yml
  when: (component == 'lcm') or
        (component == 'all')

# deploy tng-vnv-tee
- import_tasks: tee.yml
  when: (component == 'tee') or
        (component == 'all')

# deploy tng-cat
- import_tasks: cat.yml
  when: (component == 'catalogues') or
        (component == 'all')

# deploy tng-rep
- import_tasks: rep.yml
  when: (component == 'repositories') or
        (component == 'all')

# deploy tng-gtk-common
- import_tasks: gtk-common.yml
  when: (component == 'gatekeeper') or
        (component == 'gtk-common') or
        (component == 'all')

# deploy tng-gtk-vnv
- import_tasks: gtk-vnv.yml
  when: (component == 'gatekeeper') or
        (component == 'gtk-vnv') or
        (component == 'all')

# deploy Security Gateway
- import_tasks: sec-gtw.yml
  when: (component == 'gatekeeper') or
        (component == 'security-gateway') or
        (component == 'all')

# deploy tng-api-gtw
- import_tasks: api-gtw.yml
  when: (component == 'gatekeeper') or
        (component == 'gtk-api-gtw') or
        (component == 'all')

# deploy tng-sdk-pkg.yml
- import_tasks: tng-sdk-pkg.yml
  when: (component == 'gatekeeper') or
        (component == 'packager') or
        (component == 'all')

# deploy Portal
- import_tasks: portal.yml
  when: (component == 'portal') or
        (component == 'all')

# Installation Finish
- name: Installation Finish
  uri:
    url: http://bit.ly/2RCFLvj
    method: GET
    validate_certs: no
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0"
  ignore_errors: True
  when: target == "localhost"