---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: son-broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: son-broker
        platform: sonata
        version: "5"
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.6.15-management
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
        - containerPort: 4369
        - containerPort: 15672
