---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
    platform: sonata
    version: "5"
spec:
  ports:
  - port: 8086
    name: tcp-influx
    targetPort: 8086
  selector:
    app: influxdb
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: son-monitor-influxdb
  labels:
    app: influxdb
    platform: sonata
    version: "5"
spec:
  ports:
  - port: 8086
    name: tcp-influx2
    targetPort: 8086
  selector:
    app: influxdb
  type: ClusterIP
