---
apiVersion: v1
kind: Service
metadata:
  name: son-mongo
  labels:
    app: mongo
    platform: sonata
    version: "5"
spec:
  ports:
  - port: 27017
    name: mongo-mongo
    targetPort: 27017
  selector:
    app: mongo
  type: ClusterIP
