---
apiVersion: v1
kind: Service
metadata:
  name: tng-gtk-sp
  labels:
    app: tng-gtk-sp
    platform: sonata
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: tng-gtk-sp
  type: ClusterIP