---
apiVersion: v1
kind: Service
metadata:
  name: tng-sdk-package
  labels:
    app: tng-sdk-package
    platform: sonata
spec:
  ports:
  - port: 5099
    name: http
    targetPort:
  selector:
    app: tng-sdk-package
  type: ClusterIP