---
apiVersion: v1
kind: Service
metadata:
  name: tng-rep
  labels:
    app: tng-rep
    platform: sonata
    version: "5"
spec:
  ports:
  - port: 4012
    name: http-repository
    targetPort: 4012
  selector:
    app: tng-rep
  type: ClusterIP
