---
apiVersion: v1
kind: Service
metadata:
  name: tng-portal
  labels:
    app: tng-portal
    platform: sonata
    version: "5"
spec:
  ports:
  - port: 4200
    name: http-portal
  selector:
    app: tng-portal
  type: ClusterIP
