---
apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    app: broker
    platform: sonata
    version: "5"
spec:
  ports:
spec:
  type: ClusterIP
  ports:
  - name: epmd
    port: 4369
    targetPort: 4369
  - name: tcp-amqp
    port: 5672
    targetPort: 5672
  - name: tcp-stats
    port: 15672
    targetPort: 15672
  selector:
    app: son-broker
  type: ClusterIP
