---
apiVersion: v1
kind: Service
metadata:
  name: son-monitor-grafana
  labels:
    app: son-monitor-grafana
    platform: sonata
    version: "5"
spec:
  ports:
  - port: 3000
    name: http-grafana
    targetPort: 3000
  selector:
    app: son-monitor-grafana
  type: ClusterIP
