---
apiVersion: v1
kind: Service
metadata:
  name: tng-sec-gtw
  labels:
    app: tng-sec-gtw
    platform: sonata
    version: "5"
spec:
  ports:
  - port: 80
    name: http-gtw
  - port: 443
    name: https-gtw
  selector:
    app: tng-sec-gtw
  type: LoadBalancer
