---
apiVersion: v1
kind: Service
metadata:
  name: tng-cat
  labels:
    app: tng-cat
    platform: sonata
    version: "5"
spec:
  ports:
  - port: 4011
    name: http-catalogue
    targetPort: 4011
  selector:
    app: tng-cat
  type: ClusterIP
