---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
    platform: sonata
spec:
  ports:
  - port: 8086
    name: http
  selector:
    app: influxdb
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: son-monitor-influxdb
  labels:
    app: influxdb
    platform: sonata
spec:
  ports:
  - port: 8086
    name: http
  selector:
    app: influxdb
  type: NodePort