---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
    platform: sonata
spec:
  ports:
  - port: 27017
    name: http
    targetPort: 27017
  selector:
    app: mongo
  type: NodePort