---
apiVersion: v1
kind: Service
metadata:
  name: son-broker
  labels:
    app: broker
    platform: sonata
spec:
  ports:
  - port: 5672
    name: http
  - port: 15672
    name: http-api
  selector:
    app: broker
  type: NodePort